### ISSUE TITLE
makedemocerts.py requires zeroc-icecertutils 1.0.4

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice-demos#101]
If you run makedemocerts.py (from cpp98/IceGrid/secure) with zeroc-icecertutils 1.0.3, you get an unexpected arguments error:

```
./makedemocerts.py 

The subject name for your CA will be:
  CN=IceGrid Secure Demo CA,OU=Ice,O=ZeroC\, Inc.,L=Jupiter,ST=Florida,C=US

Do you want to keep this as the CA subject name? (y/n) [y] y
Traceback (most recent call last):
  File "./makedemocerts.py", line 66, in <module>
    factory.create("Master", dns="localhost", extendedKeyUsage=eku).save(os.path.join("certs", "master.p12"))
  File "/usr/lib/python2.7/site-packages/IceCertUtils/CertificateUtils.py", line 352, in create
    raise TypeError("unexpected arguments")
TypeError: unexpected arguments
```

The solution is to install zeroc-icecertutils 1.0.4:
```
sudo python -m pip install --upgrade zeroc-icecertutils
```

**Comment by externl** [comment]
Maybe we should put a `requirements.txt` in the `certs` dir?
