### ISSUE TITLE
add_signal_hanlder not available on Windows

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice-demos#131]
https://github.com/zeroc-ice/ice-demos/blob/ec06a4bb887956edce7211c4d62aa4f1e3db7239/python/Ice/async/server.py#L48
```
[ running demos from C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v140-x86-default]
(C:\Python39\python.exe -u server.py --Ice.PrintAdapterReady)
Traceback (most recent call last):
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\demoscript\ice\python\Ice\async\expect.py", line 23, in <module>
    server.expect('.* ready')
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\demoscript\demoscript\Expect.py", line 472, in expect
    raise e
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\demoscript\demoscript\Expect.py", line 465, in expect
    self.buf, self.before, self.after, self.match, self.matchindex = self.r.match(pattern, timeout)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\demoscript\demoscript\Expect.py", line 304, in match
    raise e
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\demoscript\demoscript\Expect.py", line 286, in match
    raise TIMEOUT('timeout exceeded in match\npattern: "%s"\nbuffer: "%s"\n' %
demoscript.Expect.TIMEOUT: timeout exceeded in match
pattern: ".* ready"
buffer: "Traceback (most recent call last):
  File \"C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-demos-v140-x86-default\\python\\Ice\\async\\server.py\", line 60, in <module>
    sys.exit(asyncio.run(main()))
  File \"C:\\Python39\\lib\\asyncio\\runners.py\", line 44, in run
    return loop.run_until_complete(main)
  File \"C:\\Python39\\lib\\asyncio\\base_events.py\", line 642, in run_until_complete
    return future.result()
  File \"C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-demos-v140-x86-default\\python\\Ice\\async\\server.py\", line 48, in main
    loop.add_signal_handler(signal.SIGINT, communicator.shutdown)
  File \"C:\\Python39\\lib\\asyncio\\events.py\", line 539, in add_signal_handler
    raise NotImplementedError
NotImplementedError
"
```

**Comment by bernardnormier** [comment]
Fixed.
