### ISSUE TITLE
JS demos build failure with VS2019

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-demos#51]
```
*** [6/9] building js demos (v142/x64/default)
*** building in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v142-x64-default\js
PATH = C:\Program Files\nodejs;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv;C:\tools\selenium;C:\Python37;C:\Program Files\iis express\PHP\v7.2;C:\Python37\Scripts\;C:\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\vim\vim80;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Android\android-sdk\tools\bin;;C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps;C:\Users\vagrant\AppData\Roaming\npm;C:\Program Files\ZeroC\Ice-3.7.2\bin;C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps;C:\Users\vagrant\AppData\Roaming\npm;C:\Users\vagrant\.dotnet\tools
CPP_COMPILER = v142
PLATFORM = x64
ICE_HOME = C:\Program Files\ZeroC\Ice-3.7.2
_NT_SYMBOL_PATH = C:\Users\vagrant\AppData\Local\Temp\SymbolCache
SymbolServer = SRV*%TEMP%\SymbolCache*https://builds.testing.zeroc.com/public/staging/ice/3.7/nuget/zeroc.ice.v142.store;https://symbols.zeroc.com
npm install --registry=https://builds.testing.zeroc.com/nexus/repository/npm.group-ice-3.7/ --python="C:\Python27\python" --msvs_version=2019 ice slice2js
> slice2js@3.7.2 install C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v142-x64-default\js\node_modules\slice2js
> node-gyp rebuild
C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v142-x64-default\js\node_modules\slice2js>if not defined npm_config_node_gyp (node "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
sys.exit(gyp.script_main())
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
return main(sys.argv[1:])
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
return gyp_main(args)
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
options.duplicate_basename_check)
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
generator.CalculateVariables(default_variables, params)
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
generator_flags.get('msvs_version', 'auto'))
File "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack at ChildProcess.emit (events.js:200:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vagrant\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v142-x64-default\js\node_modules\slice2js
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by pepone** [comment]
Seems like node-gyp not supporting VS 2019

**Comment by pepone** [comment]
Works locally after upgrade the node-gyp version bundled with npm to latest

```
npm install --global node-gyp@latest
for /f "delims=" %P in ('npm prefix -g') do npm config set node_gyp "%P\node_modules\node-gyp\bin\node-gyp.js"
```

I will fix Windows provisioning to do that

**Comment by pepone** [comment]
Fixed provisioning to upgrade node-gyp
