### ISSUE TITLE
JS failure to build slice2js on windows 10 / vs2019 with ice-demos/js

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice-demos#54]
```
npm install --registry=https://builds.testing.zeroc.com/nexus/repository/npm.group-ice-3.7/ --python="C:\Python27\python" --msvs_version=2019 ice slice2js
> slice2js@3.7.2 install C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v142-x64-default\js\node_modules\slice2js
> node-gyp rebuild
C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-demos-v142-x64-default\js\node_modules\slice2js>if not defined npm_config_node_gyp (node "C:\Users\vagrant\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Users\vagrant\AppData\Roaming\npm" rebuild )
internal/modules/cjs/loader.js:628
throw err;
^
Error: Cannot find module 'C:\Users\vagrant\AppData\Roaming\npm'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
at Function.Module._load (internal/modules/cjs/loader.js:527:27)
at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
at internal/main/run_main_module.js:17:11 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slice2js@3.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the slice2js@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\vagrant\AppData\Roaming\npm-cache\_logs\2019-07-12T03_49_36_479Z-debug.log
```

**Comment by pepone** [comment]
I fixed that it was a problem with provisioning not correctly setting node-gyp path in npm config. Visual Studio 2019 needs latest node-gyp.
