### ISSUE TITLE
Android hello demo crash

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice-demos#69]
Let the demo open on my phone and saw that crash, demo wasn't doing anything.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zeroc.hello, PID: 15328
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1877)
        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1900)
        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
        at android.app.BackStackRecord.commit(BackStackRecord.java:646)
        at android.app.DialogFragment.show(DialogFragment.java:235)
        at com.zeroc.hello.HelloWorld$8.handleMessage(HelloWorld.java:282)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by pepone** [comment]
Seems this happens when the applications starts while the phone is locket, android studio isn't unlocking it
