### ISSUE TITLE
cpp11/IceGrid/customLocator failure on macOS high_sierra

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice-demos#71]
This demo is failing in CI
```
Running on ice-dist-macos-high_sierra-test-3.7
*** running demo 26/37 in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/demoscript/ice/cpp11/IceGrid/customLocator
*** configuration: --mode release --fast --debug
*** demo started: 08/14/19 03:49:52
[ using Ice installation from /usr/local ]
[ running demos from /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-demos-clang-x64-default]
cleaning databases... ok
starting icegridnode... (icegridnode --Ice.Config=config.grid --Ice.PrintAdapterReady )
ok
starting custom locator... (./locator --Ice.PrintAdapterReady)
ok
deploying application... (icegridadmin --Ice.Config=config.grid)
ok
testing client without context... (./client )
ok
testing client with context... (./client --context)
Traceback (most recent call last):
File "/Users/vagrant/workspace/ice-dist/3.7/dist-utils/demoscript/ice/cpp11/IceGrid/customLocator/expect.py", line 73, in <module>
client.expect('==>')
File "/Users/vagrant/workspace/ice-dist/3.7/dist-utils/demoscript/demoscript/Expect.py", line 472, in expect
raise e
demoscript.Expect.TIMEOUT: timeout exceeded in match
pattern: "==>"
buffer: "./client: src/Ice/Network.cpp:2714: ::Ice::ConnectionRefusedException:
connection refused: Connection refused
```

I try to manually run the demo in the  VM and saw that the locator is crashing because of a missing symbol
```
./locator --Ice.PrintAdapterReady
Locator ready
dyld: lazy symbol binding failed: Symbol not found: __ZN3Ice10LocatorPrx19findObjectByIdAsyncERKNS_8IdentityENSt3__18functionIFvNS4_10shared_ptrINS_9ObjectPrxEEEEEENS5_IFvSt13exception_ptrEEENS5_IFvbEEERKNS4_3mapINS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESM_NS4_4lessISM_EENSK_INS4_4pairIKSM_SM_EEEEEE
  Referenced from: /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-demos-clang-x64-default/cpp11/IceGrid/customLocator/./locator
  Expected in: /usr/local/opt/ice/lib/libIce++11.37.dylib
```

**Comment by pepone** [comment]
This seems to work fine after a clean build
