### ISSUE TITLE
Crash when run on M OS (API 23)

### ISSUE THREAD

**Issue by daovanthe** [zeroc-ice/ice-demos#9]
**## I tried to reduce minSdkVersion from 24 to 23 in \ice-demos\java\android\talk\build.gradle for running my M Os device, The crashing occurred after launching the application! Installing APK is OK
Here is the logcat**
04-25 23:53:30.040 14547-14547/com.zeroc.talk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.zeroc.talk, PID: 14547
                                                                java.lang.NoClassDefFoundError: com.zeroc.talk.service.TalkService$$Lambda$0
                                                                    at com.zeroc.talk.service.TalkService.initialize(TalkService.java:197)
                                                                    at com.zeroc.talk.TalkActivity.serviceConnected(TalkActivity.java:378)
                                                                    at com.zeroc.talk.TalkActivity.access$200(TalkActivity.java:43)
                                                                    at com.zeroc.talk.TalkActivity$1.onServiceConnected(TalkActivity.java:123)
                                                                    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1339)
                                                                    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1356)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by daovanthe** [comment]
I tried, but there are nothing change :(

**Comment by pepone** [comment]
Can you clarify a few things:
* what Android Studio Version are you using?
* what Android version is you target device or emulator?
* what ice branch are you building from?

**Comment by daovanthe** [comment]
1. I am using AS version 3.0.1
2. My device running on M OS , 
3. I got ice-demos on the master branch, 
.. Currently , I try with other sample on demo for Java language, but 
A JNI error has occurred
Caused by: java.lang.ClassNotFoundException: com.zeroc.Ice.Object
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by pepone** [comment]
Seems you are building the demos from `java/android` this demos use the new Java mapping and require Android Nougat 7.0

For older Android versions you need to use the java-compat/android demos that use the java-compat mapping and require Android 5 (API21)

See the list of [supported platforms](https://doc.zeroc.com/display/Ice37/Supported+Platforms+for+Ice+3.7.1#SupportedPlatformsforIce3.7.1-IceforJava) for each java mapping

**Comment by daovanthe** [comment]
Thank you very much :)
